### ISSUE TITLE
different result

### ISSUE THREAD

**Issue by Wanghongyu97** [uta-smile/HGCN#1]
The results of code running on the computer and running on the server are very different. The results of running on a computer are much higher than running on a server

**Comment by viyjy** [comment]
All of our results are carried out on a server. Which dataset are you using? Can you reproduce the results reported in the paper?

**Comment by Wanghongyu97** [comment]
> All of our results are carried out on a server. Which dataset are you using? Can you reproduce the results reported in the paper?

I have reproduced the results reported in the paper on a server. But,the results of running on a computer are much higher than running on a server, such as PTC_MR.

![image](https://user-images.githubusercontent.com/67084827/117262925-5599f000-ae84-11eb-8106-cbed93eccfbf.png)(computer)
![image](https://user-images.githubusercontent.com/67084827/117262950-5cc0fe00-ae84-11eb-8270-ac205cf6d7d8.png)(server)

**Comment by viyjy** [comment]
This is so weird. Do you have GPU installed on your computer?

**Comment by Wanghongyu97** [comment]
yes
