### ISSUE TITLE
A question about experimental result 

### ISSUE THREAD

**Issue by cauny** [uta-smile/HGCN#3]
![image](https://user-images.githubusercontent.com/34748412/144696419-0fadf545-ff57-4c22-858c-48a91645b215.png)
How to compute the number behind mean accuracy? is that standard deviation or others?

And what's the number of epoches in the datasets other than IMDB-B？

Thank you very much!

**Comment by viyjy** [comment]
Our code can directly compute it. Yes, it is standard deviation.

What do you mean by "the number of epoches in the datasets"?

**Comment by cauny** [comment]
I want to know the setting of the number of epochs for each dataset.  
Because I set the epochs=1000, but can't reproduce your result

**Comment by cauny** [comment]
I just can reproduce the result of IMDB-B

**Comment by viyjy** [comment]
You can find all the commands in [script](https://github.com/uta-smile/HGCN/blob/main/script.txt).
For IMDB-B, we set epoch=100.
